#include "arduino_secrets.h"
// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "efe37339-487f-49c0-8cd8-ca45623b2f10";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


int moisture_avocado_01;
int moisture_avocado_02;
int moisture_avocado_03;
int moisture_banana;
CloudPercentage battery;
CloudRelativeHumidity humidity;
CloudTemperature temperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(moisture_avocado_01, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(moisture_avocado_02, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(moisture_avocado_03, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(moisture_banana, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(battery, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
